[phases.build]
cmds = [
  "npm ci --include=dev --ignore-scripts",
  "npm run build-css",
  "npm test",
  "npm prune --omit=dev"
]

[phases.start]
cmd = "npm start"

[variables]
NODE_ENV = "production"